### ISSUE TITLE
Missing Drawables for Network Change

### ISSUE THREAD

**Issue by behunin** [jerbeck24/Spectrum_Substratum#1]
Shamu on PN 01/21
01-24 16:35:15.464 E/AndroidRuntime(32056): android.content.res.Resources$NotFoundException: Drawable com.android.systemui:drawable/stat_sys_signal_carrier_network_change_animation with resource ID #0x7f020350

**Comment by jerbeck24** [comment]
Yeah, if on fi, don't apply the status bar icons.
